homepage:
    path: /
    defaults: { _controller: AppBundle:Default:index }

login:
    path: /login
    defaults: { _controller: AppBundle:Default:login }

test:
    path: /test
    defaults: { _controller: AppBundle:Default:test }

search:
    path: /search
    defaults: { _controller: AppBundle:Default:search }